image: oarteam/robin_ci

###############################################################################
# Variables
###############################################################################
variables:
  GIT_SUBMODULE_STRATEGY: none
  REPO_NAME: gitlab.inria.fr/batsim/batexpe
  GO_PATH: /root/go
  BATSIM_DIR: /batsim

###############################################################################
# Before script
###############################################################################
before_script:
  - export PATH="${CI_PROJECT_DIR}/artifacts:${PATH}"
  - >-
    git clone --branch v2.0.0 --depth 1 --single-branch
    https://gitlab.inria.fr/batsim/batsim.git ${BATSIM_DIR}

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    # Put batexpe source in the go source tree (so vendoring works as expected)
    - mkdir -p ${GO_PATH}/src/${REPO_NAME}
    - mv ${CI_PROJECT_DIR}/* ${GO_PATH}/src/${REPO_NAME}
    - cd ${GO_PATH}/src/${REPO_NAME}
    # Go dependencies
    - go get .
    # Prepare artifacts
    - mkdir -p ${CI_PROJECT_DIR}/artifacts
    # Build robin
    - go build -o ${CI_PROJECT_DIR}/artifacts/robin ./cmd/robin
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/artifacts/robin

###############################################################################
# Test stage
###############################################################################
cli:
  stage: test
  script:
    - robin --version
    - robin --help
    - robin -h
  dependencies:
    - build

test_should_pass:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/test/robin
    - robin batsim_nosched_ok.yaml
    - robin batsched_ok.yaml
  dependencies:
    - build
