image: oarteam/robin_ci

###############################################################################
# Variables
###############################################################################
variables:
  GIT_SUBMODULE_STRATEGY: none # TODO: set to normal (for vendoring)
  REPO_NAME: gitlab.inria.fr/batsim/batexpe
  GO_PATH: /root/go
  BATSIM_DIR: /batsim

###############################################################################
# Before script
###############################################################################
before_script:
  - export PATH="${CI_PROJECT_DIR}/artifacts:${PATH}"

###############################################################################
# Stages setup
###############################################################################
stages:
  - build
  - test
  - test_repeat

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    # Put batexpe source in the go source tree (so vendoring works as expected)
    - mkdir -p ${GO_PATH}/src/${REPO_NAME}
    - mv ${CI_PROJECT_DIR}/* ${GO_PATH}/src/${REPO_NAME}
    - cd ${GO_PATH}/src/${REPO_NAME}
    # Go dependencies
    - go get .
    # Prepare artifacts
    - mkdir -p ${CI_PROJECT_DIR}/artifacts
    # Build robin
    - go build -o ${CI_PROJECT_DIR}/artifacts/robin ./cmd/robin
    # Build robintest
    - go build -o ${CI_PROJECT_DIR}/artifacts/robintest ./cmd/robintest
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/artifacts/robin
      - ${CI_PROJECT_DIR}/artifacts/robintest

###############################################################################
# Test stage
###############################################################################
cli:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/test/robin
    - bats -p robin_cli.bats
  dependencies:
    - build

nosched:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/test/robin
    - bats -p nosched.bats
  dependencies:
    - build

batsched:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/test/robin
    - bats -p batsched_*.bats

###############################################################################
# Angry test stage
###############################################################################
nosched100:
  stage: test_repeat
  script:
    - cd ${CI_PROJECT_DIR}/test/robin
    - seq 100 | xargs -Iz bats -p nosched.bats
  dependencies:
    - build

batsched_fast50:
  stage: test_repeat
  script:
    - cd ${CI_PROJECT_DIR}/test/robin
    - seq 50 | xargs -Iz bats -p batsched_fast.bats
  dependencies:
    - build

batsched_timeout10:
  stage: test_repeat
  script:
    - cd ${CI_PROJECT_DIR}/test/robin
    - seq 10 | xargs -Iz bats -p batsched_fast.bats
  dependencies:
    - build
