image: oarteam/robin_ci

###############################################################################
# Variables
###############################################################################
variables:
  GIT_SUBMODULE_STRATEGY: none # TODO: set to normal (for vendoring)
  REPO_NAME: gitlab.inria.fr/batsim/batexpe
  GO_PATH: /root/go
  BATSIM_DIR: /batsim

###############################################################################
# Before script
###############################################################################
before_script:
  # Put batexpe source in the go source tree
  - export CI_PROJECT_DIR_GOPATH="${GO_PATH}/src/${REPO_NAME}"
  - mkdir -p ${CI_PROJECT_DIR_GOPATH}
  - mv ${CI_PROJECT_DIR}/* ${CI_PROJECT_DIR_GOPATH}
  - cd ${CI_PROJECT_DIR_GOPATH}
  # Path on steroids
  - export PATH="${CI_PROJECT_DIR_GOPATH}/artifacts:/root/go/bin:${PATH}"

###############################################################################
# Stages setup
###############################################################################
stages:
  - build
  - test
  - coverage

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    # Go dependencies
    - go get .
    # Prepare artifacts
    - mkdir -p ${CI_PROJECT_DIR}/artifacts
    # Build robin
    - go build -o ${CI_PROJECT_DIR}/artifacts/robin ./cmd/robin
    # Build robintest
    - go build -o ${CI_PROJECT_DIR}/artifacts/robintest ./cmd/robintest
    # Build robin.cover (robin with coverage)
    - go test -c -o ${CI_PROJECT_DIR}/artifacts/robin.cover -covermode=count -coverpkg=./,./cmd/robin,./cmd/robintest ./cmd/robin
    # Build robintest.cover (robintest with coverage)
    - go test -c -o ${CI_PROJECT_DIR}/artifacts/robintest.cover -covermode=count -coverpkg=./,./cmd/robin,./cmd/robintest ./cmd/robintest
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/artifacts/robin
      - ${CI_PROJECT_DIR}/artifacts/robintest
      - ${CI_PROJECT_DIR}/artifacts/robin.cover
      - ${CI_PROJECT_DIR}/artifacts/robintest.cover

###############################################################################
# Test stage
###############################################################################
cli:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR_GOPATH}/test/robin
    - bats robin_cli.bats
  dependencies:
    - build

nosched:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR_GOPATH}/test/robin
    - bats nosched.bats
  dependencies:
    - build

batsched:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR_GOPATH}/test/robin
    - bats batsched_*.bats

###############################################################################
# Coverage
###############################################################################

coverage:
  stage: coverage
  script:
    - cd ${CI_PROJECT_DIR_GOPATH}/test/robin
    - ./cover.bash
    - cat coverage-report.txt
    - cp merged.covout coverage-report.txt ${CI_PROJECT_DIR}/
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/merged.covout
      - ${CI_PROJECT_DIR}/coverage-report.txt
  dependencies:
    - build
